import { Instructor } from 'src/app/Shared/models/instuctorInfo';

export const instructorConst: Instructor[] = [
  {
    firstName: 'Mike',
    lastName: 'Romables',
    location: 'San Diego, CA',
    imgPath: 'assets/images/mike.jpg',
    level: 'advanced',
    blurb: 'he does this and that',
    contact: 'somewhere@somewhere.com',
  },

  {
    firstName: 'Rick',
    lastName: 'Rogers',
    location: 'Wilkes-Barre, PA',
    imgPath: 'assets/images/frame.jpg',
    level: 'advanced',
    blurb: 'he does stuff too',
    contact: 'hereandthere@gmail.com',
  },
  {
    firstName: 'Seth',
    lastName: 'Mutschler',
    location: 'Idaho/Eastern Oregon',
    imgPath: 'assets/images/seth.jpg',
    level: 'intermediate',
    blurb: 'he does stuff too',
    contact: 'hereandthere@gmail.com',
  },
  {
    firstName: 'Ben',
    lastName: 'Whitney',
    location: 'Denver, CO',
    imgPath: 'assets/images/frame.jpg',
    level: 'apprentice',
    blurb: 'he does stuff too',
    contact: 'hereandthere@gmail.com',
  },
  {
    firstName: 'Rachel',
    lastName: 'Mahloch',
    location: 'Boulder, CO',
    imgPath: 'assets/images/Rachel.jpg',
    level: 'apprentice',
    blurb: 'she does stuff too',
    contact: 'hereandthere@gmail.com',
  },
  {
    firstName: 'Walker',
    lastName: 'Wilder',
    location: 'Burlington, VT',
    imgPath: 'assets/images/frame.jpg',
    level: 'apprentice',
    blurb: 'he does stuff too',
    contact: 'hereandthere@gmail.com',
  },
  {
    firstName: 'Ryan',
    lastName: 'Smith',
    location: 'Golden, CO',
    imgPath: 'assets/images/ryan.JPG',
    level: 'apprentice',
    blurb: 'he does stuff too',
    contact: 'hereandthere@gmail.com',
  },
];
